### PR TITLE
added Spanish translations

### PR DESCRIPTION
**Pull request by fermuch**
It's not complete, but almost all the strings are translated.

That HTML with Javascript is just nasty. I'm not sure if it is intended to be that way, or I did something wrong with ```update_po.sh```.

### CODE REVIEW

**Comment by gerard-** [comment]
Thanks! I'll merge this later today.

You did nothing wrong, there is still some HTML code floating around from the old site. I tried to convert all pages to Markdown for easier translation but for some pages that was a bit more work as they were using javascript. I hope I can get them all done soon!

**Comment by gerard-** [comment]
It looks like you only translated the stuff that was already in the (out of date) dutch translation. Is that correct? Having just these texts translated is already nice though as we can't re-use the translations from the old site for them.

When I run update_po.sh myself there are a lot more translatable strings. The messages.po file is generated in the root directory, you'll have to import it yourself.

**Comment by fermuch** [comment]
Whoops! I thought messages.po in the root folder was just garbage. I'll keep translating these strings this night or tomorrow. Now I see a more of text :tongue: 

Is there a reason to **not** use something like Transifex? Freenet already uses that platform, and it keeps things simple for translators who are not devs.

**Comment by gerard-** [comment]
No, there is no specific reason. I know Freenet uses Transifex but I don't know exactly how to use it myself. I'll ask one of the devs. I've added some tips for translators to the readme, might be useful.

**Pull request merged**
